---
abstract: 'Localized number formatters using the Unicode CLDR'
author:
  - 'Nick Patch <patch@cpan.org>'
build_requires:
  Pod::Man: 2.04
  Test::Exception: 0.22
  Test::More: 0.82
  Test::Warn: 0.01
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CLDR-Number
provides:
  CLDR::Number:
    file: lib/CLDR/Number.pm
    version: 0.01
  CLDR::Number::Data::Base:
    file: lib/CLDR/Number/Data/Base.pm
    version: 0.01
  CLDR::Number::Data::Currency:
    file: lib/CLDR/Number/Data/Currency.pm
    version: 0.01
  CLDR::Number::Format::Currency:
    file: lib/CLDR/Number/Format/Currency.pm
    version: 0.01
  CLDR::Number::Format::Decimal:
    file: lib/CLDR/Number/Format/Decimal.pm
    version: 0.01
  CLDR::Number::Format::Percent:
    file: lib/CLDR/Number/Format/Percent.pm
    version: 0.01
  CLDR::Number::Role::Base:
    file: lib/CLDR/Number/Role/Base.pm
    version: 0.01
  CLDR::Number::Role::Format:
    file: lib/CLDR/Number/Role/Format.pm
    version: 0.01
requires:
  Carp: 0
  Math::BigFloat: 0
  Math::Round: 0
  Moo: 1.000000
  Moo::Role: 0
  Scalar::Util: 0
  charnames: 0
  namespace::clean: 0
  perl: v5.8.1
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/perl-cldr/cldr-number-perl5/issues
  homepage: https://github.com/perl-cldr/cldr-number-perl5
  license: http://dev.perl.org/licenses/
  repository: git://github.com/perl-cldr/cldr-number-perl5.git
version: 0.01
